import Head from "next/head"; // Import the Head component
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Existing and additional meta tags here */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Meta tags for iOS WebApp */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        {/* Ensure you include viewport meta for responsive design */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
